# Generated by Django 2.0 on 2017-08-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0002_article_pub_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(default='2017-08-30 09:59:30'),
        ),
    ]
